import React, { useState } from 'react';
import { AppDatabase, Evaluation, User } from '../types';
import { calculateAllBranchesAutoEvaluations, BranchAutoEvaluation } from '../utils/evaluationCalculator';
import { 
  Award, 
  Star, 
  CheckCircle2, 
  Trash2, 
  Calendar, 
  MessageSquare, 
  Store,
  Sparkles,
  TrendingUp,
  TrendingDown,
  AlertTriangle,
  RotateCcw,
  ShieldCheck,
  Percent,
  CheckCircle,
  FileCheck2,
  BookmarkCheck
} from 'lucide-react';

interface EvaluationsTabProps {
  db: AppDatabase;
  onUpdateDb: (updater: (prev: AppDatabase) => AppDatabase) => void;
  adminUsername: string;
  currentUser?: User;
}

export const EvaluationsTab: React.FC<EvaluationsTabProps> = ({ 
  db, 
  onUpdateDb, 
  adminUsername,
  currentUser 
}) => {
  const [success, setSuccess] = useState('');
  const [showManualForm, setShowManualForm] = useState(false);
  const [selectedBranchId, setSelectedBranchId] = useState<string>(
    db.branches[0] ? String(db.branches[0].id) : ''
  );
  const [manualScore, setManualScore] = useState<number | ''>('');
  const [manualFeedback, setManualFeedback] = useState('');

  // Calculate live automatic evaluations for all branches
  const autoEvaluations = calculateAllBranchesAutoEvaluations(db);

  const showSuccess = (msg: string) => {
    setSuccess(msg);
    setTimeout(() => setSuccess(''), 3500);
  };

  // Sync / Publish an Automated Evaluation to Official Archive
  const handlePublishAutoEvaluation = (autoEval: BranchAutoEvaluation) => {
    const newId = db.evaluations.length ? Math.max(...db.evaluations.map(e => e.id)) + 1 : 1;
    const now = new Date();
    const dateStr = now.toLocaleDateString('tr-TR') + ' ' + now.toLocaleTimeString('tr-TR', { hour: '2-digit', minute: '2-digit' });

    const newEval: Evaluation = {
      id: newId,
      branchId: autoEval.branchId,
      score: autoEval.performanceScore,
      feedback: autoEval.systemFeedback,
      date: dateStr,
      evaluator: `Sistem Otomatik Değerlendirme (${adminUsername})`,
      accuracyRate: autoEval.stockAccuracyRate,
      totalItems: autoEval.totalAssigned,
      exactMatches: autoEval.exactMatches,
      discrepancyCount: autoEval.shortageCount + autoEval.surplusCount,
      isAutoGenerated: true,
      grade: autoEval.grade
    };

    onUpdateDb(prev => ({
      ...prev,
      evaluations: [newEval, ...prev.evaluations]
    }));

    showSuccess(`"${autoEval.branchName}" için otomatik başarı puanı (${autoEval.performanceScore}/100) resmi arşive kaydedildi.`);
  };

  // Publish All Automatic Evaluations at Once
  const handlePublishAllAutoEvaluations = () => {
    const now = new Date();
    const dateStr = now.toLocaleDateString('tr-TR') + ' ' + now.toLocaleTimeString('tr-TR', { hour: '2-digit', minute: '2-digit' });

    const newRecords: Evaluation[] = autoEvaluations.map((ae, idx) => ({
      id: (db.evaluations.length ? Math.max(...db.evaluations.map(e => e.id)) : 0) + idx + 1,
      branchId: ae.branchId,
      score: ae.performanceScore,
      feedback: ae.systemFeedback,
      date: dateStr,
      evaluator: `Sistem Otomatik Algoritması (${adminUsername})`,
      accuracyRate: ae.stockAccuracyRate,
      totalItems: ae.totalAssigned,
      exactMatches: ae.exactMatches,
      discrepancyCount: ae.shortageCount + ae.surplusCount,
      isAutoGenerated: true,
      grade: ae.grade
    }));

    onUpdateDb(prev => ({
      ...prev,
      evaluations: [...newRecords, ...prev.evaluations]
    }));

    showSuccess(`Tüm mağazaların (${autoEvaluations.length} şube) otomatik performans değerlendirmeleri resmi arşive işlendi.`);
  };

  // Manual Evaluation Save (optional)
  const handleSaveManualEvaluation = (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedBranchId) {
      alert('Lütfen mağaza seçiniz.');
      return;
    }
    const scoreNum = Number(manualScore);
    if (isNaN(scoreNum) || scoreNum < 0 || scoreNum > 100) {
      alert('Lütfen 0 ile 100 arasında geçerli bir puan giriniz.');
      return;
    }

    const newId = db.evaluations.length ? Math.max(...db.evaluations.map(e => e.id)) + 1 : 1;
    const now = new Date();
    const dateStr = now.toLocaleDateString('tr-TR');

    const newEval: Evaluation = {
      id: newId,
      branchId: Number(selectedBranchId),
      score: scoreNum,
      feedback: manualFeedback.trim() || 'Merkez yönetim özel denetim değerlendirmesi yapıldı.',
      date: dateStr,
      evaluator: adminUsername,
      isAutoGenerated: false
    };

    onUpdateDb(prev => ({
      ...prev,
      evaluations: [newEval, ...prev.evaluations]
    }));

    showSuccess('Özel yönetim performans değerlendirmesi kaydedildi.');
    setManualScore('');
    setManualFeedback('');
    setShowManualForm(false);
  };

  const handleDeleteEvaluation = (id: number) => {
    // Check permission
    const isSuperAdmin = currentUser?.isSuperAdmin || currentUser?.username.toUpperCase() === 'O.BAS' || currentUser?.username.toUpperCase() === 'T.CESUR';
    const canDelete = isSuperAdmin || currentUser?.permissions?.canDeleteCounts;

    if (!canDelete) {
      alert('Yetki Kısıtlaması: Değerlendirme kayıtlarını silme yetkiniz bulunmamaktadır. Yetki için yöneticiler (O.BAS / T.CESUR) ile iletişime geçiniz.');
      return;
    }

    onUpdateDb(prev => ({
      ...prev,
      evaluations: prev.evaluations.filter(e => e.id !== id)
    }));
    showSuccess('Değerlendirme arşivi güncellendi.');
  };

  return (
    <div className="space-y-6 max-w-6xl">
      {success && (
        <div className="p-4 bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-semibold rounded-2xl flex items-center gap-2 animate-fadeIn shadow-xs">
          <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
          <span>{success}</span>
        </div>
      )}

      {/* Top Banner: Automated Evaluation Engine Overview */}
      <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <div className="p-2.5 bg-indigo-50 text-indigo-600 rounded-2xl">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-extrabold text-slate-900 tracking-tight flex items-center gap-2">
                <span>Otomatik Mağaza Başarı & Performans Değerlendirme Sistemi</span>
                <span className="text-[10px] bg-emerald-50 text-emerald-700 font-bold px-2 py-0.5 rounded-full border border-emerald-200">
                  Otomatik Hesaplama Aktif
                </span>
              </h2>
              <p className="text-xs text-slate-500 mt-0.5">
                Mağaza başarı puanı ve denetim notları, personelin sayım doğruluğuna ve merkez stok mutabakatına göre sistem tarafından otomatik hesaplanır.
              </p>
            </div>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={handlePublishAllAutoEvaluations}
            className="flex items-center gap-1.5 px-4 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-xs font-bold shadow-md shadow-indigo-600/20 transition cursor-pointer"
            title="Tüm mağazaların güncel otomatik puanlarını resmi arşive kaydet"
          >
            <BookmarkCheck className="w-4 h-4" />
            <span>Tümünü Arşive İşle</span>
          </button>

          <button
            onClick={() => setShowManualForm(!showManualForm)}
            className="flex items-center gap-1.5 px-3.5 py-2.5 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl text-xs font-bold transition cursor-pointer"
          >
            <span>{showManualForm ? 'Formu Gizle' : '+ Özel Not Ekle'}</span>
          </button>
        </div>
      </div>

      {/* Calculation Criteria Explanatory Card */}
      <div className="bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 text-white p-4 sm:p-5 rounded-2xl shadow-md border border-indigo-500/20 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="space-y-1">
          <span className="text-[10px] font-bold uppercase tracking-wider text-indigo-300">
            Otomatik Değerlendirme Puanlama Formülü
          </span>
          <p className="text-xs text-slate-200 font-medium">
            Başarı Puanı = (%45 Tam Eşleşme Oranı) + (%35 Stok Doğruluk Oranı) + (%20 Sayım Tamamlama Oranı)
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-3 text-xs">
          <div className="px-2.5 py-1 rounded-lg bg-white/10 text-emerald-300 font-bold border border-white/10">
            A+ (%95-100): Kusursuz
          </div>
          <div className="px-2.5 py-1 rounded-lg bg-white/10 text-indigo-300 font-bold border border-white/10">
            A (%85-94): Yüksek Başarı
          </div>
          <div className="px-2.5 py-1 rounded-lg bg-white/10 text-amber-300 font-bold border border-white/10">
            B (%70-84): Kabul Edilebilir
          </div>
          <div className="px-2.5 py-1 rounded-lg bg-white/10 text-rose-300 font-bold border border-white/10">
            C/D (&lt;%70): İnceleme Gerekli
          </div>
        </div>
      </div>

      {/* Optional Manual Audit Form */}
      {showManualForm && (
        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm space-y-4 animate-fadeIn">
          <h3 className="font-bold text-slate-900 text-sm flex items-center gap-2">
            <Star className="w-4 h-4 text-amber-500 fill-amber-500" />
            <span>Özel Yönetim Denetim Notu Girişi</span>
          </h3>

          <form onSubmit={handleSaveManualEvaluation} className="space-y-4 pt-2">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-bold text-slate-600 uppercase mb-1.5">
                  Şube / Mağaza
                </label>
                <select
                  value={selectedBranchId}
                  onChange={e => setSelectedBranchId(e.target.value)}
                  className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs outline-none focus:bg-white focus:ring-2 focus:ring-indigo-500 font-medium"
                  required
                >
                  <option value="">Şube Seçin</option>
                  {db.branches.map(b => (
                    <option key={b.id} value={b.id}>{b.name} ({b.code})</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-600 uppercase mb-1.5">
                  Özel Puan (0 - 100)
                </label>
                <input
                  type="number"
                  min="0"
                  max="100"
                  placeholder="Örn: 90"
                  value={manualScore}
                  onChange={e => setManualScore(e.target.value === '' ? '' : Number(e.target.value))}
                  className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs font-bold outline-none focus:bg-white focus:ring-2 focus:ring-indigo-500"
                  required
                />
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-600 uppercase mb-1.5">
                Yönetici Notu & Geri Bildirimi
              </label>
              <textarea
                rows={2}
                placeholder="Özel denetim notunuzu yazınız..."
                value={manualFeedback}
                onChange={e => setManualFeedback(e.target.value)}
                className="w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-xs outline-none focus:bg-white focus:ring-2 focus:ring-indigo-500"
              />
            </div>

            <div className="flex justify-end gap-2">
              <button
                type="button"
                onClick={() => setShowManualForm(false)}
                className="px-4 py-2 bg-slate-100 text-slate-700 text-xs font-bold rounded-xl"
              >
                İptal
              </button>
              <button
                type="submit"
                className="px-6 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold rounded-xl shadow-sm transition cursor-pointer"
              >
                Özel Değerlendirmeyi Kaydet
              </button>
            </div>
          </form>
        </div>
      )}

      {/* ========================================================================= */}
      {/* REAL-TIME AUTOMATED PERFORMANCE EVALUATIONS CARDS (ŞUBE BAZINDA OTOMATİK)  */}
      {/* ========================================================================= */}
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <h3 className="font-extrabold text-sm text-slate-900 tracking-tight flex items-center gap-2">
            <Award className="w-4 h-4 text-indigo-600" />
            <span>Şube Bazında Güncel Otomatik Başarı Değerlendirmeleri ({autoEvaluations.length} Şube)</span>
          </h3>
          <span className="text-[11px] text-slate-400 font-mono">
            Sayım doğruluğuna göre anlık güncellenir
          </span>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          {autoEvaluations.map(ae => {
            let badgeBg = 'bg-rose-50 text-rose-700 border-rose-200';
            let gradeBadge = 'bg-rose-600 text-white';

            if (ae.statusColor === 'emerald') {
              badgeBg = 'bg-emerald-50 text-emerald-800 border-emerald-200';
              gradeBadge = 'bg-emerald-600 text-white';
            } else if (ae.statusColor === 'indigo') {
              badgeBg = 'bg-indigo-50 text-indigo-800 border-indigo-200';
              gradeBadge = 'bg-indigo-600 text-white';
            } else if (ae.statusColor === 'amber') {
              badgeBg = 'bg-amber-50 text-amber-800 border-amber-200';
              gradeBadge = 'bg-amber-600 text-white';
            }

            return (
              <div
                key={ae.branchId}
                className="bg-white p-5 rounded-3xl border border-slate-200 shadow-sm space-y-4 hover:border-slate-300 transition"
              >
                {/* Header: Branch Name, Code, Score & Grade */}
                <div className="flex items-start justify-between gap-3 border-b border-slate-100 pb-3.5">
                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      <Store className="w-4 h-4 text-indigo-600 shrink-0" />
                      <h4 className="font-extrabold text-sm text-slate-900">
                        {ae.branchName}
                      </h4>
                      <span className="text-[10px] bg-slate-100 text-slate-600 font-mono px-2 py-0.5 rounded-md font-bold">
                        {ae.branchCode}
                      </span>
                    </div>

                    <p className="text-[11px] text-slate-500">
                      {ae.gradeTitle}
                    </p>
                  </div>

                  {/* Big Score Box */}
                  <div className="flex items-center gap-2 shrink-0">
                    <div className="text-right">
                      <span className="text-[10px] text-slate-400 font-semibold block uppercase">
                        Otomatik Puan
                      </span>
                      <span className="text-xl font-black text-slate-900 font-mono">
                        {ae.performanceScore}
                        <span className="text-xs text-slate-400 font-normal"> / 100</span>
                      </span>
                    </div>

                    <div className={`w-11 h-11 rounded-2xl flex items-center justify-center font-black text-sm shadow-sm ${gradeBadge}`}>
                      {ae.grade}
                    </div>
                  </div>
                </div>

                {/* Accuracy Metrics Grid */}
                <div className="grid grid-cols-3 gap-2.5 text-center">
                  <div className="p-2.5 bg-slate-50 rounded-2xl border border-slate-100">
                    <span className="text-[10px] text-slate-500 font-medium block">Tam Eşleşme</span>
                    <strong className="text-xs font-black text-emerald-700 font-mono block mt-0.5">
                      %{ae.exactMatchRate}
                    </strong>
                    <span className="text-[9px] text-slate-400 font-mono">({ae.exactMatches} kalem)</span>
                  </div>

                  <div className="p-2.5 bg-slate-50 rounded-2xl border border-slate-100">
                    <span className="text-[10px] text-slate-500 font-medium block">Stok Doğruluğu</span>
                    <strong className="text-xs font-black text-indigo-700 font-mono block mt-0.5">
                      %{ae.stockAccuracyRate}
                    </strong>
                    <span className="text-[9px] text-slate-400 font-mono">(Mutlak adet)</span>
                  </div>

                  <div className="p-2.5 bg-slate-50 rounded-2xl border border-slate-100">
                    <span className="text-[10px] text-slate-500 font-medium block">Tamamlama</span>
                    <strong className="text-xs font-black text-slate-800 font-mono block mt-0.5">
                      %{ae.completenessRate}
                    </strong>
                    <span className="text-[9px] text-slate-400 font-mono">({ae.totalCountedItems}/{ae.totalAssigned})</span>
                  </div>
                </div>

                {/* Automated System Feedback Box */}
                <div className={`p-3.5 rounded-2xl border text-xs leading-relaxed space-y-1 ${badgeBg}`}>
                  <div className="flex items-center gap-1.5 font-bold">
                    <Sparkles className="w-3.5 h-3.5" />
                    <span>Sistem Otomatik Değerlendirme Raporu</span>
                  </div>
                  <p className="text-[11px]">
                    {ae.systemFeedback}
                  </p>
                </div>

                {/* Footer Actions */}
                <div className="flex items-center justify-between pt-1 text-xs">
                  <span className="text-[10px] text-slate-400 font-mono">
                    {ae.lastCountTime ? `Son Sayım: ${ae.lastCountTime}` : 'Henüz sayım girilmedi'}
                  </span>

                  <button
                    onClick={() => handlePublishAutoEvaluation(ae)}
                    className="flex items-center gap-1 px-3 py-1.5 bg-slate-100 hover:bg-indigo-600 hover:text-white text-slate-700 rounded-xl text-[11px] font-bold transition cursor-pointer"
                  >
                    <FileCheck2 className="w-3.5 h-3.5" />
                    <span>Resmi Arşive Kaydet</span>
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* ========================================================================= */}
      {/* HISTORICAL EVALUATION ARCHIVE                                             */}
      {/* ========================================================================= */}
      <div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-6 space-y-4">
        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <h4 className="font-extrabold text-sm text-slate-900 tracking-tight flex items-center gap-2">
            <Award className="w-4 h-4 text-indigo-600" />
            <span>Kayıtlı Değerlendirme ve Denetim Arşivi ({db.evaluations.length})</span>
          </h4>
          <span className="text-xs text-slate-400">
            Mağaza personelinin görebildiği resmi kayıtlar
          </span>
        </div>

        {db.evaluations.length === 0 ? (
          <p className="text-xs text-slate-400 py-6 text-center">Henüz arşive işlenmiş bir değerlendirme bulunmuyor.</p>
        ) : (
          <div className="space-y-3">
            {db.evaluations.map(ev => {
              const branch = db.branches.find(b => b.id === ev.branchId);

              return (
                <div
                  key={ev.id}
                  className="p-4 rounded-2xl border border-slate-100 bg-slate-50/70 hover:bg-slate-50 transition flex items-start justify-between gap-4"
                >
                  <div className="space-y-1.5">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="font-bold text-slate-900 text-xs">
                        {branch?.name || 'Bilinmeyen Şube'}
                      </span>
                      <span className="px-2.5 py-0.5 rounded-full text-[11px] font-black bg-indigo-100 text-indigo-800 font-mono">
                        {ev.score} / 100 Puan
                      </span>
                      {ev.grade && (
                        <span className="px-2 py-0.5 rounded-md text-[10px] font-black bg-emerald-600 text-white">
                          Derece: {ev.grade}
                        </span>
                      )}
                      <span className="text-[10px] text-slate-400 flex items-center gap-1 font-mono">
                        <Calendar className="w-3 h-3" /> {ev.date}
                      </span>
                    </div>

                    <p className="text-xs text-slate-700 leading-relaxed">
                      "{ev.feedback}"
                    </p>

                    {ev.evaluator && (
                      <p className="text-[10px] text-slate-400 font-medium">
                        Değerlendiren / Kaynak: {ev.evaluator}
                      </p>
                    )}
                  </div>

                  <button
                    onClick={() => handleDeleteEvaluation(ev.id)}
                    className="p-1.5 text-slate-400 hover:text-rose-600 hover:bg-rose-50 rounded-lg transition cursor-pointer shrink-0"
                    title="Bu değerlendirmeyi sil"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
};
