export interface Branch {
  id: number;
  name: string;
  code: string;
  city?: string;
  createdAt?: string;
}

export interface Aisle {
  id: number;
  name: string;
  description?: string;
}

export interface UserPermissions {
  canDeleteCounts?: boolean;
  canEditCounts?: boolean;
  canEditProducts?: boolean;
  canDeleteProducts?: boolean;
  canImportExcel?: boolean;
  canManageBranches?: boolean;
  canDeleteBranches?: boolean;
  canManageAisles?: boolean;
  canManageUsers?: boolean;
  canExportReports?: boolean;
  canViewReports?: boolean;
  canEvaluateBranches?: boolean;
  canApproveCounts?: boolean;
}

export interface User {
  id: number;
  username: string;
  password: string;
  role: 'admin' | 'store';
  branchId?: number | null;
  fullName?: string;
  isSuperAdmin?: boolean;
  permissions?: UserPermissions;
}

export interface Product {
  id: number;
  barcode: string;
  stockCode: string;
  description: string;
  centralStock: number;
  aisleId: number;
  unit?: string;
  category?: string;
  color?: string;
}

export interface Assignment {
  branchId: number;
  productId: number;
}

export interface CountRecord {
  id: number;
  branchId: number;
  productId: number;
  quantity: number;
  countedAt: string;
  counterName?: string;
  notes?: string;
}

export interface Evaluation {
  id: number;
  branchId: number;
  score: number;
  feedback: string;
  date: string;
  evaluator?: string;
  accuracyRate?: number;
  totalItems?: number;
  exactMatches?: number;
  discrepancyCount?: number;
  isAutoGenerated?: boolean;
  grade?: 'A+' | 'A' | 'B' | 'C' | 'D' | string;
}

export interface BranchCountStatus {
  branchId: number;
  isCompleted: boolean;
  completedAt?: string;
  completedBy?: string;
  batchId?: string;
  totalQty?: number;
  distinctItems?: number;
}

export interface AppDatabase {
  branches: Branch[];
  aisles: Aisle[];
  users: User[];
  products: Product[];
  assignments: Assignment[];
  counts: CountRecord[];
  evaluations: Evaluation[];
  branchStatuses?: BranchCountStatus[];
  currentBatchId?: string;
  lastSentAt?: string;
}
